# Generated by Django 4.2.10 on 2024-02-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
