# Generated by Django 4.2.10 on 2024-02-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_habitacion_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
